In [40]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Concatenate Matrix

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
df = DataFrame(np.arange(9).reshape(3,3))
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [71]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(9).reshape(3,3)

In [72]:
np.concatenate((arr1,arr2))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.concatenate((arr1,arr2),axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

# Concatenate Series

In [19]:
s1 = Series([1,2,3],index = ['x','y','z'])
s2 = Series([4,5],index = ['a','b'])

In [20]:
s1

x    1
y    2
z    3
dtype: int64

In [21]:
s2

a    4
b    5
dtype: int64

In [22]:
pd.concat((s1,s2))

x    1
y    2
z    3
a    4
b    5
dtype: int64

In [27]:
pd.concat((s1,s2),axis=1)

0    1
a  NaN  4.0
b  NaN  5.0
x  1.0  NaN
y  2.0  NaN
z  3.0  NaN

# Concatenate Dataframe

In [41]:
df1 = DataFrame(np.random.randn(4,3),columns = ['x','y','z'])
df2 = DataFrame(np.random.randn(3,3),columns = ['x','y','a'])

In [42]:
df1

x         y         z
0 -0.443054  0.808065 -0.592195
1 -0.174658  0.221322  0.121333
2  0.343527  0.465841  2.146078
3  0.913177 -0.572143 -0.232101

In [46]:
df2

x         y         a
0 -0.995899  0.358935  0.875438
1 -1.116787  0.529407  0.170557
2  0.162065  1.072613  0.626409

In [49]:
pd.concat((df1,df2))

a         x         y         z
0       NaN -0.443054  0.808065 -0.592195
1       NaN -0.174658  0.221322  0.121333
2       NaN  0.343527  0.465841  2.146078
3       NaN  0.913177 -0.572143 -0.232101
0  0.875438 -0.995899  0.358935       NaN
1  0.170557 -1.116787  0.529407       NaN
2  0.626409  0.162065  1.072613       NaN

# Combine Series

In [50]:
s1 =Series([2,np.nan,4,np.nan],index = ['a','b','c','d'])
s2 =Series([1,2,3,4],index = ['a','b','c','d'])

In [51]:
s1

a    2.0
b    NaN
c    4.0
d    NaN
dtype: float64

In [52]:
s2

a    1
b    2
c    3
d    4
dtype: int64

In [53]:
s1.combine_first(s2)  # use s2 to fill NaN in s1

a    2.0
b    2.0
c    4.0
d    4.0
dtype: float64

# Combine Dataframe

In [73]:
df1 = DataFrame({
    'x':[1,np.nan,3,np.nan],
    'y':[5,np.nan,7,np.nan],
    'z':['9',5,11,np.nan]
})

In [74]:
df1

x    y    z
0  1.0  5.0    9
1  NaN  NaN    5
2  3.0  7.0   11
3  NaN  NaN  NaN

In [75]:
df2 = DataFrame({
    'z':[np.nan,10,np.nan,12],
    'a':[1,2,3,4]
})

In [76]:
df2

a     z
0  1   NaN
1  2  10.0
2  3   NaN
3  4  12.0

In [77]:
df1.combine_first(df2)

a    x    y   z
0  1.0  1.0  5.0   9
1  2.0  NaN  NaN   5
2  3.0  3.0  7.0  11
3  4.0  NaN  NaN  12