In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Concatenate Matrix

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
df = DataFrame(np.arange(9).reshape(3,3))
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [6]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(9).reshape(3,3)

In [12]:
np.concatenate((arr1,arr2))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.concatenate((arr1,arr2),axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

# Concatenate Series

In [19]:
s1 = Series([1,2,3],index = ['x','y','z'])
s2 = Series([4,5],index = ['a','b'])

In [20]:
s1

x    1
y    2
z    3
dtype: int64

In [21]:
s2

a    4
b    5
dtype: int64

In [22]:
pd.concat((s1,s2))

x    1
y    2
z    3
a    4
b    5
dtype: int64

In [27]:
pd.concat((s1,s2),axis=1)

0    1
a  NaN  4.0
b  NaN  5.0
x  1.0  NaN
y  2.0  NaN
z  3.0  NaN