# 快速创建数组


In [1]:
import numpy as np

In [2]:
np.random.randn(10) # len of the random number is 10

array([ 1.35083386, -0.37200141,  0.88384268, -0.45910082, -0.30832341,
       -0.91054191, -0.45029476,  2.7246251 , -0.45688846,  0.48423019])

In [16]:
np.random.randint(1,5) # random  int number betwen 1 and 5 , 1 included, 5 not

1

In [5]:
np.random.randint(10, size=(2,3))  # size - dimention 

array([[7, 6, 5],
       [6, 7, 1]])

In [23]:
np.random.randint(10, size=20) # 1D array with the len of 20

array([2, 1, 0, 3, 0, 2, 1, 2, 9, 4, 7, 8, 1, 3, 0, 7, 8, 8, 2, 2])

In [21]:
np.random.randint(10, size=20).reshape(4,5) # 1D array with the len of 20 =>  2D array with 4*5

array([[6, 0, 4, 2, 1],
       [0, 9, 0, 2, 5],
       [4, 8, 5, 0, 5],
       [7, 3, 5, 6, 4]])

In [24]:
np.random.randint(5,10, size=20).reshape(4,5) # 1D array (range in 5-10),with the len of 20 =>  2D array with 4*5

array([[9, 7, 7, 8, 9],
       [8, 8, 7, 6, 6],
       [8, 8, 7, 8, 7],
       [8, 5, 9, 6, 7]])

# 数组运算


In [26]:
a = np.random.randint(5,10, size=20).reshape(4,5)
b = np.random.randint(5,10, size=20).reshape(4,5)

In [27]:
a


array([[5, 8, 9, 8, 5],
       [8, 6, 8, 7, 6],
       [5, 9, 5, 8, 8],
       [8, 7, 6, 7, 5]])

In [28]:
b

array([[7, 8, 8, 9, 8],
       [6, 6, 8, 7, 5],
       [6, 5, 6, 9, 8],
       [6, 7, 5, 9, 9]])

In [30]:
a+b

array([[12, 16, 17, 17, 13],
       [14, 12, 16, 14, 11],
       [11, 14, 11, 17, 16],
       [14, 14, 11, 16, 14]])

In [31]:
a-b

array([[-2,  0,  1, -1, -3],
       [ 2,  0,  0,  0,  1],
       [-1,  4, -1, -1,  0],
       [ 2,  0,  1, -2, -4]])

In [32]:
a*b

array([[35, 64, 72, 72, 40],
       [48, 36, 64, 49, 30],
       [30, 45, 30, 72, 64],
       [48, 49, 30, 63, 45]])

In [33]:
a/b

array([[ 0.71428571,  1.        ,  1.125     ,  0.88888889,  0.625     ],
       [ 1.33333333,  1.        ,  1.        ,  1.        ,  1.2       ],
       [ 0.83333333,  1.8       ,  0.83333333,  0.88888889,  1.        ],
       [ 1.33333333,  1.        ,  1.2       ,  0.77777778,  0.55555556]])

# 矩阵及矩阵运算

In [34]:
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [35]:
a

array([[5, 8, 9, 8, 5],
       [8, 6, 8, 7, 6],
       [5, 9, 5, 8, 8],
       [8, 7, 6, 7, 5]])

In [36]:
np.mat(a)

matrix([[5, 8, 9, 8, 5],
        [8, 6, 8, 7, 6],
        [5, 9, 5, 8, 8],
        [8, 7, 6, 7, 5]])

In [37]:
A = np.mat(a)
B = np.mat(b)

In [38]:
A

matrix([[5, 8, 9, 8, 5],
        [8, 6, 8, 7, 6],
        [5, 9, 5, 8, 8],
        [8, 7, 6, 7, 5]])

In [39]:
B

matrix([[7, 8, 8, 9, 8],
        [6, 6, 8, 7, 5],
        [6, 5, 6, 9, 8],
        [6, 7, 5, 9, 9]])

In [40]:
A+B

matrix([[12, 16, 17, 17, 13],
        [14, 12, 16, 14, 11],
        [11, 14, 11, 17, 16],
        [14, 14, 11, 16, 14]])

In [41]:
A-B

matrix([[-2,  0,  1, -1, -3],
        [ 2,  0,  0,  0,  1],
        [-1,  4, -1, -1,  0],
        [ 2,  0,  1, -2, -4]])

In [42]:
A*B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [43]:
a = np.mat(np.random.randint(5,10, size=20).reshape(4,5))
b = np.mat(np.random.randint(5,10, size=20).reshape(5,4))

In [44]:
a

matrix([[8, 7, 7, 7, 8],
        [6, 6, 8, 9, 7],
        [9, 5, 9, 8, 5],
        [7, 7, 6, 9, 7]])

In [45]:
b

matrix([[8, 5, 9, 5],
        [5, 9, 8, 5],
        [5, 5, 5, 6],
        [8, 8, 5, 5],
        [9, 7, 8, 8]])

In [46]:
a*b

matrix([[262, 250, 262, 216],
        [253, 245, 243, 209],
        [251, 234, 246, 204],
        [256, 249, 250, 207]])

# Array 常见函数

In [47]:
a= np.random.randint(5,10, size=20).reshape(4,5)

In [50]:
a

array([[7, 8, 6, 5, 5],
       [7, 6, 5, 9, 8],
       [8, 7, 7, 7, 8],
       [9, 9, 9, 8, 5]])

In [51]:
np.unique(a)

array([5, 6, 7, 8, 9])

In [52]:
sum(a)   #  list sum 

array([31, 30, 27, 29, 26])

In [53]:
sum(a[0]) # sum of list in  0 position(row)

31

In [54]:
sum(a[:,0]) # sum of column in 0 postion

31

In [56]:
a.max()

9

In [92]:
min(a[0])

5

In [93]:
np.unique(a[0])

array([5, 6, 7, 8])

In [58]:
max(a[:,0])

9

In [73]:
mt = np.mat([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[1, 2, 3]]
])

ValueError: matrix must be 2-dimensional

In [63]:
array = np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[1, 2, 3]]
])

In [64]:
array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [67]:
array.shape

(2, 2, 3)

In [84]:
mt = np.mat([[1, 2],[3, 4]])
array = np.array([[1, 2],[3, 4]])

In [85]:
mt

matrix([[1, 2],
        [3, 4]])

In [86]:
array

array([[1, 2],
       [3, 4]])

In [87]:
mt = np.mat([[1, 'a'],[3, 4]])
array = np.array([[1, 'a'],[3, 4]])

In [88]:
mt  

matrix([['1', 'a'],
        ['3', '4']], 
       dtype='<U21')

In [89]:
array

array([['1', 'a'],
       ['3', '4']], 
      dtype='<U21')