# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
# create array from python list
list_1 = [1, 2, 3, 4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)

In [5]:
array_1

array([1, 2, 3, 4])

In [51]:
list_2 = [5, 6, 7, 8]

In [52]:
array_2 = np.array([list_1, list_2])

In [53]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
array_2.shape

(2, 4)

In [55]:
array_2.size

8

In [56]:
array_2.dtype

dtype('int64')

In [60]:
array_3 = np.array([[1.0, 2, 3], [4.0, 5, 6],[7.0, 8, 9]])

In [66]:
list_1 = [1, 2, 3]
list_2 = [3, 4, 5]

list_11 = [list_1, list_2]
list_22 = [list_1, list_2]

list_111 = [list_11, list_22, list_11]

array_111 = np.array(list_111)

list_1111 = [list_111, list_111]
array_1111 = np.array(list_1111)

In [64]:
array_111.shape

(3, 2, 3)

In [65]:
array_111.size

18

In [68]:
array_1111.shape

(2, 3, 2, 3)

In [72]:
array_222 = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [7, 8, 9]], 
    [[7, 8, 9], [7, 8, 8]], 
    [[6, 2, 2], [1, 2, 3.0]]
])

array_222.shape

(4, 2, 3)

In [74]:
list_a = [1, 2, 3]
list_b = [1, 2, ]

list_aa = [list_a, list_b]

In [79]:
array_aa = np.array(list_aa)
array_aa

array([[1, 2, 3], [1, 2]], dtype=object)

In [78]:
array_aa.shape

(2,)

In [80]:
array_222.dtype

dtype('float64')

In [84]:
array_4 = np.arange(1, 10, 2)

In [85]:
array_4

array([1, 3, 5, 7, 9])

In [86]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [88]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [89]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [90]:
np.eye(5).dtype

dtype('float64')

In [91]:
a = np.arange(1,10)

In [92]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a[2]

3

In [104]:
a[:5]

array([1, 2, 3, 4, 5])

In [95]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [96]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
b[1][0]

4

In [98]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [99]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
c[2:,2:]

array([[9]])

In [101]:
c[2,1]

8

In [102]:
c[2][1]

8

In [103]:
c[1:2,]

array([[4, 5, 6]])