In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])  # 一维数组
arr1  # array对象，是数组或数组嵌套

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])  #二维数组
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
arr3 = np.array([1,2,3,4,5],ndmin =2)  # ndmin=2 至少二维
arr3

array([[1, 2, 3, 4, 5]])

In [10]:
arr4 = np.array([1,2,3,4,5],dtype='complex')  #实数
arr4

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])