In [22]:
import numpy as np
a = np.arange(12)
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
for i in np.nditer(a): # 遍历每个元素
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
print(a.T) #转制

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [26]:
for i in np.nditer(a.T): #遍历每个元素，与矩阵的shape无关
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
a = a.reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
b = a.copy()
b
print(b)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]


In [29]:
c = b.copy(order = 'C') #C风格copy，从左往右，从上到下
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [30]:
c = b.copy(order = 'F')  # F风格copy从上往下，从左到右
for i in np.nditer(c):
    print(i)

0
6
1
7
2
8
3
9
4
10
5
11


In [31]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
for i in np.nditer(a,order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [33]:
for i in np.nditer(a,order='F'):
    print(i)

0
6
1
7
2
8
3
9
4
10
5
11


In [34]:
for i in np.nditer(a,order='F'):
    i = 10
    print(i)

10
10
10
10
10
10
10
10
10
10
10
10


In [35]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [36]:
for i in np.nditer(a,op_flags = ['readwrite']): #op_flags 设置修改原来的数据
    i[...]= 2*i
    print(i) 

0
2
4
6
8
10
12
14
16
18
20
22


In [38]:
for i in np.nditer(a,flags = ['external_loop']):  # 返回一维数组
    print(i)  

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [40]:
for i in np.nditer(a,flags = ['c_index']):  # 返回C风格的单个元素
    print(i)  

0
1
2
3
4
5
6
7
8
9
10
11


In [41]:
for i in np.nditer(a,flags = ['f_index']):  # 返回F风格单个元素
    print(i)  

0
1
2
3
4
5
6
7
8
9
10
11


In [48]:
a = np.arange(12)
a = a.reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [49]:
for i in np.nditer(a,op_flags = ['readwrite']): #op_flags 设置修改原来的数据
    i[...]= 2*i
    print(i) 

0
2
4
6
8
10
12
14
16
18
20
22


In [50]:
a

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [51]:
b = np.array([1,1,1,1,1,1,])
print(a+b)

[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]


In [55]:
for x,y in np.nditer([a,b]): #广播迭代，循环迭代，列数相同
    print(x,y)

0 1
2 1
4 1
6 1
8 1
10 1
12 1
14 1
16 1
18 1
20 1
22 1


In [76]:
data = [[x,y] for x,y in np.nditer([a,b])]
print(x,y)

[0 1 2 3 4 5 6 7 8 9] 1


In [73]:
data = [x for x in range(10)]
data
#print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [74]:
x = [1,2,3,4,5]
x
#print(x)

[1, 2, 3, 4, 5]

In [75]:
x = np.arange(10)
x
#print(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])