In [8]:
import numpy as np
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
b = np.broadcast(x,y) #对y广播x
b.index
print(b.__next__()) #循环下一个
print(b.__next__())
print(b.__next__())
print(b.__next__()) #循环下一个
print(b.__next__())
print(b.__next__())
print(b.__next__()) #循环下一个
print(b.__next__())
print(b.__next__())
print(b.index) #索引位置

(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)
9


In [10]:
print(b.shape)

(3, 3)


In [11]:
b = np.broadcast(x,y)
c = np.empty(b.shape) #清空

In [13]:
b,c

(<numpy.broadcast at 0x7fd1d1080220>,
 array([[3.10503618e+231, 4.33972231e-311, 2.47032823e-323],
        [0.00000000e+000, 2.12199579e-314, 1.16096346e-028],
        [1.04857803e-142, 1.16467185e-028, 9.15806241e+135]]))

In [14]:
c.shape

(3, 3)

In [17]:
c.flat = [u+v for (u,v) in b] # 数组的加法
c

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [18]:
a = np.arange(4).reshape(1,4)
a

array([[0, 1, 2, 3]])

In [20]:
print(np.broadcast_to(a,(5,4))) #实现数组的复制，列数相同

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [22]:
x = np.array(([1,2],[3,4]))
x #二维数组  几个中括号就是几维

array([[1, 2],
       [3, 4]])

In [23]:
y = np.expand_dims(x, axis=0)  #插入一个坐标轴
y #三维数组

array([[[1, 2],
        [3, 4]]])

In [24]:
y = np.expand_dims(x, axis=1)
y #三维数组

array([[[1, 2]],

       [[3, 4]]])

In [25]:
y = np.expand_dims(x, axis=2)
y #三维数组

array([[[1],
        [2]],

       [[3],
        [4]]])

In [26]:
x = np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
print(x.shape)

(3, 3, 3)


In [28]:
y = np.squeeze(x)
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
y.shape

(3, 3, 3)

In [30]:
x = np.arange(27).reshape(1,3,9)
x

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [31]:
y = np.squeeze(x)  #外层只有一个元素，可以删除一个维度
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])