In [1]:
import numpy as np


In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [6]:
print(np.concatenate((a,b))) #按照行concatenate

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
print(np.concatenate((a,b),axis = 1))  # 按照列concate


[[1 2 5 6]
 [3 4 7 8]]


In [8]:
np.stack((a,b),0)  # 沿新轴连接数组序列，按轴0（行），两个二维变成一个三维

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
np.stack((a,b),1) #按轴1（行），同上

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [10]:
np.hstack((a,b)) #保持二维数组，按列横向叠加

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
np.vstack((a,b)) #保持二维数组，按行纵向叠加

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
b = np.split(a,10) #切割为10个数组
b
#print(b)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [17]:
c = np.split(a,[30,60,80]) #z按照位置切割
c

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99])]

In [20]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
b = np.hsplit(a,2) #按照列切割，必须能够整除
b

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [23]:
b = np.vsplit(a,2) #按照行切割，必须可整除
b

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b =np.resize(a,(3,3)) #改变数组形状
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
b.shape,a.shape

((3, 3), (9,))

In [31]:
b = np.resize(a,(3,4)) # 返回指定大小的新数组，如果新数组大小大于原始数组，则用数据循环填充
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [32]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.append(a,10) # 增加一个元素，copy到新数组

array([ 1,  2,  3,  4,  5,  6, 10])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
b = np.append(a,[10,11,12])  #增加一个数组，copy到新数组
b

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b = np.append(a,[[7,8,9]],axis= 0 ) # 0轴为x轴。添加行

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b = np.append(a,[[17,18,19],[100,101,102]],axis= 1 )  按照面
b 

array([[  1,   2,   3,  17,  18,  19],
       [  4,   5,   6, 100, 101, 102]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.insert(a,2,[100,101]) #新建数组，按照数据位置插入，即在2的后面插入100，101

array([  1,   2, 100, 101,   3,   4,   5,   6])

In [47]:
np.insert(a,1,[10000],axis=0) # x轴插入一整行

array([[    1,     2,     3],
       [10000, 10000, 10000],
       [    4,     5,     6]])

In [50]:
np.insert(a,1,[100,1000,10000],axis=0)

array([[    1,     2,     3],
       [  100,  1000, 10000],
       [    4,     5,     6]])

In [51]:
np.insert(a,1,[[100,1000],[1000,1000 ]],axis=1) # 插入一个面

array([[   1,  100, 1000,    2,    3],
       [   4, 1000, 1000,    5,    6]])

In [52]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [54]:
np.delete(a,0,axis=0) #删除含有0的行

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.delete(a,1,axis=1) #删除含有1的列

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [56]:
a = np.array([1,2,3,4,1,2,3,4,5,6])
a

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [57]:
print(np.unique(a))

[1 2 3 4 5 6]


In [59]:
u,index = np.unique(a,return_index=True) # 原油数组索引，位置数
index

array([0, 1, 2, 3, 8, 9])

In [61]:
u

array([1, 2, 3, 4, 5, 6])

In [63]:
print(a[index]) #在原有数组中选择不重复的索引数据

[1 2 3 4 5 6]


In [64]:
u,indexid = np.unique(a,return_inverse=True)
indexid

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5])

In [65]:
a[indexid]  #根据下标重建数组

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2])

In [67]:
u,nums = np.unique(a,return_counts=True) #返回重复次数 
nums 

array([2, 2, 2, 2, 1, 1])