In [1]:
import numpy as np

In [3]:
myArr = np.array([0,30,60,45,90,150,180,360])
myArr

array([  0,  30,  60,  45,  90, 150, 180, 360])

In [4]:
np.pi #pi = 180

3.141592653589793

In [5]:
np.sin(myArr*np.pi/180)

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  7.07106781e-01,
        1.00000000e+00,  5.00000000e-01,  1.22464680e-16, -2.44929360e-16])

In [6]:
np.cos(myArr*np.pi/180)

array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  7.07106781e-01,
        6.12323400e-17, -8.66025404e-01, -1.00000000e+00,  1.00000000e+00])

In [7]:
np.tan(myArr*np.pi/180)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.00000000e+00,
        1.63312394e+16, -5.77350269e-01, -1.22464680e-16, -2.44929360e-16])

In [9]:
sin = np.sin(myArr*np.pi/180)

In [11]:
inv = np.arcsin(sin)
inv

array([ 0.00000000e+00,  5.23598776e-01,  1.04719755e+00,  7.85398163e-01,
        1.57079633e+00,  5.23598776e-01,  1.22464680e-16, -2.44929360e-16])

In [12]:
np.degrees(inv)

array([ 0.00000000e+00,  3.00000000e+01,  6.00000000e+01,  4.50000000e+01,
        9.00000000e+01,  3.00000000e+01,  7.01670930e-15, -1.40334186e-14])

In [13]:
myArr =np.array([1.1,5.5,12.3,25,0.78,29.3])
myArr

array([ 1.1 ,  5.5 , 12.3 , 25.  ,  0.78, 29.3 ])

In [14]:
np.around(myArr)

array([ 1.,  6., 12., 25.,  1., 29.])

In [15]:
np.around(myArr,decimals=1) #保留一位小数

array([ 1.1,  5.5, 12.3, 25. ,  0.8, 29.3])

In [16]:
np.around(myArr,decimals=-1) #-1 是对个位数清零，5.1进位，5.0不进位

array([ 0., 10., 10., 20.,  0., 30.])