In [1]:
import numpy as np
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
arr2 = np.array([10,20,30,40])
arr2

array([10, 20, 30, 40])

In [3]:
np.add(arr1,arr2)

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51],
       [22, 33, 44, 55]])

In [4]:
arr3 = np.array([[10,20,30,40],[10,20,30,40],[10,20,30,40],[10,20,30,40]])
arr3

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [5]:
np.add(arr1,arr3)

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51],
       [22, 33, 44, 55]])

In [9]:
np.divide(arr1,arr2)

array([[0.        , 0.05      , 0.06666667, 0.075     ],
       [0.4       , 0.25      , 0.2       , 0.175     ],
       [0.8       , 0.45      , 0.33333333, 0.275     ],
       [1.2       , 0.65      , 0.46666667, 0.375     ]])

In [10]:
np.reciprocal(arr1)

/Users/dante/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.
/Users/dante/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[-9223372036854775808,                    1,                    0,
                           0],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
                           0]])

In [11]:
arr1 = np.arange(16,dtype = float).reshape(4,4)

In [12]:
np.reciprocal(arr1)

/Users/dante/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [13]:
a = np.array([100,200,300])
b = np.array([1,2,3])

In [14]:
np.power(a,2)

array([10000, 40000, 90000])

In [15]:
np.power(a,b)

array([     100,    40000, 27000000])

In [17]:
a = np.array([100,200,300])
b = np.array([11,12,13])
np.mod(a,b)

array([1, 8, 1])

In [18]:
complex = np.array([1-5.6j,1+2j,11,1+1j])
complex

array([ 1.-5.6j,  1.+2.j , 11.+0.j ,  1.+1.j ])

In [19]:
np.real(complex)

array([ 1.,  1., 11.,  1.])

In [20]:
np.imag(complex)

array([-5.6,  2. ,  0. ,  1. ])

In [21]:
np.angle(complex)

array([-1.39408747,  1.10714872,  0.        ,  0.78539816])