In [1]:
import numpy as np

In [2]:
myArr = np.array([[11,21,2],[111,11,222],[33,44,32]])
myArr

array([[ 11,  21,   2],
       [111,  11, 222],
       [ 33,  44,  32]])

In [3]:
np.amax(myArr)

222

In [4]:
np.amin(myArr)

2

In [9]:
np.amin(myArr,axis=0) # 0为列最小值，1为行最小值

array([11, 11,  2])

In [10]:
np.ptp(myArr)  #最大值与最小值之差

220

In [12]:
np.ptp(myArr,0)

array([100,  33, 220])

In [13]:
np.percentile(myArr,100) #按照人群比例求百分比，100为100%

222.0

In [15]:
np.percentile(myArr,70,axis=0)

array([ 64.2,  30.2, 108. ])

In [16]:
np.median(myArr)

32.0

In [17]:
np.median(myArr,0)

array([33., 21., 32.])

In [18]:
myArr

array([[ 11,  21,   2],
       [111,  11, 222],
       [ 33,  44,  32]])

In [19]:
np.mean(myArr)

54.111111111111114

In [20]:
np.mean(myArr,0)

array([51.66666667, 25.33333333, 85.33333333])

In [21]:
a = np.array([6,7,8,9,10]) 
b = np.array([10,1,2,3,4])
np.average(a,weights=b) 
#加权平均值, (6*10+7*1+8*2……+10*4）/（10+1+2+3+4）

7.5

In [22]:
np.std([4,4,4,4])
#标准差，描述平均程度，方差越小越平均。标准差是与均值的偏差的平方的平均值的# 平方根

0.0

In [23]:
np.std([4,4,4,10004]) # std  = sqrt(mean(x-x.mean())**2))

4330.127018922193

In [24]:
np.std([94,84,74,104])

11.180339887498949

In [25]:
np.var([4,4,4,4])

0.0

In [27]:
np.var([4,4,4,20]) #方差是偏差的平方的平均值 var = mean((x-x.mean())**2)

48.0

In [ ]:
x-8