In [1]:
import numpy as np

In [7]:
a = np.array([[3,9,0],[1,8,2]])
a

array([[3, 9, 0],
       [1, 8, 2]])

In [8]:
print(np.sort(a))

[[0 3 9]
 [1 2 8]]


In [10]:
print(np.sort(a,axis=0)) #0列排序，1行排序

[[1 8 0]
 [3 9 2]]


In [14]:
dt = np.dtype([('name','S10'),('age',int),('tall',int)])
a  = np.array([('fengjie',33,160),('chunge',28,170),
               ('furong',30,180)],dtype=dt)

In [15]:
np.sort(a,order='name')

array([(b'chunge', 28, 170), (b'fengjie', 33, 160), (b'furong', 30, 180)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('tall', '<i8')])

In [16]:
np.sort(a,order='age')

array([(b'chunge', 28, 170), (b'furong', 30, 180), (b'fengjie', 33, 160)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('tall', '<i8')])

In [17]:
np.sort(a,order='tall')

array([(b'fengjie', 33, 160), (b'chunge', 28, 170), (b'furong', 30, 180)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('tall', '<i8')])

In [18]:
np.sort(a,kind='heapsort',order = 'tall')

array([(b'fengjie', 33, 160), (b'chunge', 28, 170), (b'furong', 30, 180)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('tall', '<i8')])

In [19]:
np.sort(a,kind='mergesort',order = 'tall')

array([(b'fengjie', 33, 160), (b'chunge', 28, 170), (b'furong', 30, 180)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('tall', '<i8')])

In [20]:
x = np.array([2,1,4,3])
x

array([2, 1, 4, 3])

In [21]:
y = np.argsort(x) #索引排序，位置是按照value排序
y

array([1, 0, 3, 2])

In [23]:
x[y]

array([1, 2, 3, 4])

In [24]:
x

array([2, 1, 4, 3])

In [26]:
np.argmax(x) #取出最大值的索引

2

In [27]:
np.argmin(x)

1

In [29]:
np.nonzero(x) #数组中不为零的索引

(array([0, 1, 2, 3]),)

In [30]:
np.nonzero(np.array([0,1,0,1]))

(array([1, 3]),)

In [32]:
ind = np.lexsort(np.array([4,1,3,2]))
print(ind)

0


In [33]:
nm=('B','A','D','C')
dv = ('1','2','3','4')
ind = np.lexsort((dv,nm))
print(ind)

[1 0 3 2]


In [34]:
[nm[i] + ',' + dv[i] for i in ind]

['A,2', 'B,1', 'C,4', 'D,3']

In [35]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
y = np.where(x>5)
y #索引，对应【20，21，22】

(array([2, 2, 2]), array([0, 1, 2]))

In [38]:
cond =np.mod(x,2) == 0
np.extract(cond,x) #挖掘所有条件成立的

array([0, 2, 4, 6, 8])