# 创建自定义数组对象

In [1]:
import numpy as np
data1 = np.dtype(np.int32) # 数组的索引大小32,使用dtype主要目的是节约内存
print(data1)

int32


In [3]:
data1 =np.dtype('i2') #int8,int16,int32,int64可替换为等价字符串'i1'，'i2'，'i4','i8'
print(data1) # 年龄-int8 0-256（2^8)

int16


In [4]:
data1 =np.dtype('>i4')
print(data1)

>i4


In [7]:
data2 = np.dtype([('tall',np.int16)])  # tuple
data2

dtype([('tall', '<i2')])

In [8]:
dt = np.dtype([(('age',np.int8))]) # 创建符合类型，描述表头
ageArr = np.array([(10,),(20,),(30,)],dtype=dt) # 创建一个数组，为dtype类型
ageArr #（10，）<---> ageArr['age']

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [9]:
ageArr['age']

array([10, 20, 30], dtype=int8)

In [10]:
student = np.dtype([('name','S20'),('age','i4'),('money','f4')]) #自定义数据类型,S20代表字符串的宽度
student

dtype([('name', 'S20'), ('age', '<i4'), ('money', '<f4')])

In [11]:
studentArr = np.array([('huanjian',88,12345.45),('yinzheng','35',1235566.56)],dtype=student) # 创建自定义类型的数组
studentArr

array([(b'huanjian', 88,   12345.45), (b'yinzheng', 35, 1235566.5 )],
      dtype=[('name', 'S20'), ('age', '<i4'), ('money', '<f4')])

In [12]:
studentArr['name']  #取出数组中的某段

array([b'huanjian', b'yinzheng'], dtype='|S20')

In [13]:
studentArr['age']

array([88, 35], dtype=int32)

In [14]:
studentArr['money' ]

array([  12345.45, 1235566.5 ], dtype=float32)