In [2]:
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
id(a)

4574257520

In [6]:
b = a  #视图，共享内存,数据改变，ab一起改变，结构改变，一起改变
id(b)

4574257520

In [7]:
a[3] =1000
b

array([   0,    1,    2, 1000,    4,    5])

In [8]:
a.shape

(6,)

In [9]:
b.shape

(6,)

In [11]:
a.shape=(2,3)

In [12]:
b.shape

(2, 3)

In [14]:
c = a. view() #c 是 a的视图，数据改变一起改变，形状改变，视图不变
c

array([[   0,    1,    2],
       [1000,    4,    5]])

In [16]:
a.shape=(6,)
a

array([   0,    1,    2, 1000,    4,    5])

In [17]:
c #保留原来的视图，但是数据不变 

array([[   0,    1,    2],
       [1000,    4,    5]])

In [18]:
a[0]=-1
c

array([[  -1,    1,    2],
       [1000,    4,    5]])

In [22]:

d = c[:,:2]
d


array([[  -1,    1],
       [1000,    4]])

In [3]:
e = a.copy()  #deep copy,原本的改变不影响副本
e

array([0, 1, 2, 3, 4, 5])

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5])

In [7]:
e

array([0, 1, 2, 3, 4, 5])