In [1]:
import numpy as np
import numpy.matlib   #数据计算
import numpy.matrixlib  #矩阵

In [2]:
myArr = np.matlib.empty((3,3)) # 填充随机数据
myArr  

matrix([[2.00000000e+000, 2.00000000e+000, 2.96439388e-323],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [2.00000000e+000, 2.00000000e+000, 1.55092132e+184]])

In [4]:
myArr = np.matlib.zeros((3,3)) 
myArr

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
myArr = np.matlib.ones((3,3)) 
myArr

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
myArr = np.matlib.eye(n= 3,M=5,k=0,dtype = float)  #填充对角线
myArr

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [12]:
myArr = np.matlib.identity(5,dtype = float)
myArr # 方阵，对角线直接取，不限制行列深度 

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
myArr= np.matlib.rand(5,5)  #随机数矩阵
myArr

matrix([[0.28294285, 0.304175  , 0.49936129, 0.05820678, 0.5274203 ],
        [0.41451372, 0.0975426 , 0.20687723, 0.10771002, 0.79674495],
        [0.35600358, 0.05999579, 0.06949141, 0.23827692, 0.49777537],
        [0.79886633, 0.8544731 , 0.94679633, 0.49116061, 0.65513058],
        [0.1714025 , 0.11846738, 0.35422553, 0.7590292 , 0.6369309 ]])

In [15]:
myMatrix = np.matrix('1,2;3,4')
myMatrix

matrix([[1, 2],
        [3, 4]])

In [16]:
myArr = np.asarray(myMatrix)
myArr #矩阵转化为数组，矩阵是二维数组

array([[1, 2],
       [3, 4]])

In [17]:
newMatrix = np. asmatrix(myArr)
newMatrix #数组转化为矩阵

matrix([[1, 2],
        [3, 4]])