In [1]:
import numpy as np
import numpy.matlib

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
a

array([[1, 2],
       [3, 4]])

In [2]:
b

array([[11, 12],
       [13, 14]])

In [3]:
np.dot(a,b)  # 同矩阵乘法，内积

array([[37, 40],
       [85, 92]])

In [4]:
np.vdot(a,b) # 横X横并相加

130

In [5]:
np.inner(np.array([1,2,3]),np.array([0,1,0]))

2

In [6]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

In [8]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.matmul(a,b)  #矩阵的乘法

array([[4, 1],
       [2, 2]])

In [9]:
a = np.array([[1,2],[3,4]])
np.linalg.det(a) # 行列式，对角线相乘后相减

-2.0000000000000004

In [11]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
x

array([[1, 2],
       [3, 4]])

In [12]:
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
np.matmul(x,y)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])