# 数组的维度

In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape  #维度，2行3列

(2, 3)

In [7]:
a.size #元素数

6

In [9]:
newa = np.array([[1,2,3],[4,5,6]])
newa.shape = (3,2)  # 动态调整维度。3行2列
newa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
newa.reshape(6,1)  # 动态调整维度

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
makea = np.arange(24) # 动态创建连续数组
makea

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
makea.reshape(4,6) #不会改变原来的数组维度，1维

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
makea.ndim # 查看数组维度

1

In [16]:
makea = makea.reshape(4,6)
makea

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
makea.ndim

2

In [18]:
makea = makea.reshape(2,3,4)
makea

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
makea.ndim

3

In [21]:
makea.itemsize

8

In [25]:
x = np.array([1,2,3,4,5],dtype=np.int64)
print(x.itemsize)

8


In [26]:
print(x.flags)  #flags 属性描述

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

