In [1]:
import numpy as np

In [6]:
x = np.empty([3,2],dtype= int)  #随机抓去内存，没有清零
x

array([[-3458764513820540928, -3458764513820540928],
       [     140534426370053,   794321336339270912],
       [ 3275354340909339414,           1701869908]])

In [7]:
x = np.zeros(15) # 清零的实数 15个， 0. 表示实数, zero表示用0填充
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
x = np.zeros( (15,), dtype = np.int) # 清零的证整数。15个
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
x = np.zeros((3,3),dtype=([('tall','f4'),('age','i4'),('money','f4')])) # 自定义类型创建数组，初始化
x

array([[(0., 0, 0.), (0., 0, 0.), (0., 0, 0.)],
       [(0., 0, 0.), (0., 0, 0.), (0., 0, 0.)],
       [(0., 0, 0.), (0., 0, 0.), (0., 0, 0.)]],
      dtype=[('tall', '<f4'), ('age', '<i4'), ('money', '<f4')])

In [11]:
x['tall']

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [12]:
x = np.ones(5)  # 用1 填充
x

array([1., 1., 1., 1., 1.])

In [14]:
x = np.ones([5,5],dtype=np.int)  # [5,5]与(5,5)结果一致
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])