# asarray将已有python序列(list,tuple）转化为ndarry 

In [1]:
import numpy as np
x = [1,2,3,4,5]
arr1 = np.asarray(x)
print(arr1)

[1 2 3 4 5]


In [4]:
arr1 = np.asarray(x,dtype=np.float)  # type是实数，1.
print(arr1)
arr1

[1. 2. 3. 4. 5.]


array([1., 2., 3., 4., 5.])

In [5]:
y = (1,2,3,4,5) #tuple
arr1 = np.asarray(y)
print(arr1)
arr1

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [8]:
z = [(1,2,3,4,5),(6,7,8)]
arr1 = np.asarray(z)
print(arr1)
arr1

[(1, 2, 3, 4, 5) (6, 7, 8)]


array([(1, 2, 3, 4, 5), (6, 7, 8)], dtype=object)

#

In [12]:
myName = 'Sam'
myNamenp = np.frombuffer(myName,dtype='S1')  # S1 是一个字符,按照1个1个字符切割
print(myNamenp)  #python3已经不支持frombuffer了

TypeError: a bytes-like object is required, not 'str'

# 根据iterator创建array

In [13]:
myList = [x for x in range(10)]
print(myList)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
it = iter(myList)
xArray = np.fromiter(it,dtype=np.int)
print(xArray)

[0 1 2 3 4 5 6 7 8 9]
