In [2]:
import numpy as np
x = np.arange(5)

In [3]:
x

array([0, 1, 2, 3, 4])

In [4]:
x = np.arange(1,100,3)  # start, stop, step
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [5]:
x = np.arange(1,100,3,dtype = np.float)
x

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [7]:
y = np.linspace(10,20,10) #10与20之间，切割为10段，不是step（步长）
print(y)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [10]:
y = np.linspace(10,20,10, endpoint = False)  # endponit是否包含最后一个元素，false为不包括
print(y)  

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [14]:
y = np.linspace(10,20,10, endpoint = False，retstep = True)  # endponit是否包含最后一个元素，false为不包括
print(y)  # retstep = True 插入切割的步长

SyntaxError: invalid character in identifier (<ipython-input-14-31a68b986b40>, line 1)

In [16]:
z = np.logspace(1.0,2.0,num = 10) # 默认底数为10
z

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [19]:
z = np.logspace(1.0,2.0,num = 10, base = 5)   #指数级增长
z

array([ 5.        ,  5.97906587,  7.14984574,  8.54987973, 10.22405883,
       12.22606424, 14.62008869, 17.48289467, 20.90627577, 25.        ])

In [20]:
z = np.logspace(1,10,num=10,base=2) #从2^1 ----> 2^10, base是底数，num是次数
z

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])