In [3]:
import numpy as np

In [4]:
myArr  = np.arange(10)
myArr
print(myArr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
s = slice(2,7,2) # 2-7之间，不包含7，每次+2
print(type(s)) #class 'slice' 索引
myArr[s]

<class 'slice'>


array([2, 4, 6])

In [7]:
myArr[2:7:3]  # 等价与slice（2，7，3）

array([2, 5])

In [10]:
print(myArr[::]) 

[0 1 2 3 4 5 6 7 8 9]


In [11]:
myArr[4]

4

In [12]:
myArr[:]  #显示全部

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myArr[2:-1]  # stop在倒数第二个位置

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
myArr[2:5]

array([2, 3, 4])

In [6]:
myArr = np.arange(20)
myArr.shape=(4,5)
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
myArr[0] # 取出二维数组中的一维数组

array([0, 1, 2, 3, 4])

In [7]:
myArr[2][1:3] #取出二维数组中某一行的某一个序列

array([11, 12])

In [10]:
myArr[0:2]  #二维数组

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
myArr[0:2][0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
myArr[0:2][1:3]  #非横纵列筛选，还是在[0:2]筛选之后的二维数组上，再次进行[1;3]的筛选

array([[5, 6, 7, 8, 9]])

In [15]:
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
myArr[::2] # 2为步长

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [17]:
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
myArr[1,...] # 取出第二行

array([5, 6, 7, 8, 9])

In [19]:
myArr[...,1] # 取出第二列

array([ 1,  6, 11, 16])

In [20]:
myArr[1:3,...]  #1-2行

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
myArr[...,1:3] # 1-2列

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [22]:
myArr[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [3]:
import tushare as ts
stock = ts.get_hist_data('600848')
stock

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>close</th>
      <th>low</th>
      <th>volume</th>
      <th>price_change</th>
      <th>p_change</th>
      <th>ma5</th>
      <th>ma10</th>
      <th>ma20</th>
      <th>v_ma5</th>
      <th>v_ma10</th>
      <th>v_ma20</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-04-17</th>
      <td>19.50</td>
      <td>19.76</td>
      <td>19.52</td>
      <td>19.42</td>
      <td>30986.41</td>
      <td>0.08</td>
      <td>0.41</td>
      <td>19.386</td>
      <td>19.487</td>
      <td>19.372</td>
      <td>27932.33</td>
      <td>29716.51</td>
      <td>40609.42</td>
    </tr>
    <tr>
      <th>2020-04-16</th>
      <td>19.34</td>
      <td>19.61</td>
      <td>19.44</td>
      <td>19.25</td>
      <td>19242.38</td>
      <td>-0.07</td>
      <td>-0.36</td>
      <td>19.384</td>
      <td>19.495</td>
      <td>19.356</td>
      <td>28713.78</td>
      <td>30451.68</td>
      <td>42135.92</td>
    </tr>
    <tr>
      <th>2020-04-15</th>
      <td>19.35</td>
      <td>19.99</td>
      <td>19.51</td>
      <td>19.26</td>
      <td>42097.65</td>
      <td>0.16</td>
      <td>0.83</td>
      <td>19.410</td>
      <td>19.500</td>
      <td>19.344</td>
      <td>29794.98</td>
      <td>34737.28</td>
      <td>43578.49</td>
    </tr>
    <tr>
      <th>2020-04-14</th>
      <td>19.20</td>
      <td>19.36</td>
      <td>19.35</td>
      <td>19.12</td>
      <td>24102.21</td>
      <td>0.24</td>
      <td>1.26</td>
      <td>19.418</td>
      <td>19.559</td>
      <td>19.339</td>
      <td>27476.99</td>
      <td>42044.24</td>
      <td>44088.32</td>
    </tr>
    <tr>
      <th>2020-04-13</th>
      <td>19.48</td>
      <td>19.48</td>
      <td>19.11</td>
      <td>19.01</td>
      <td>23232.98</td>
      <td>-0.40</td>
      <td>-2.05</td>
      <td>19.500</td>
      <td>19.584</td>
      <td>19.361</td>
      <td>29939.95</td>
      <td>48381.43</td>
      <td>46148.55</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2017-10-24</th>
      <td>28.20</td>
      <td>28.75</td>
      <td>28.05</td>
      <td>27.22</td>
      <td>313290.41</td>
      <td>-1.74</td>
      <td>-5.84</td>
      <td>27.804</td>
      <td>27.804</td>
      <td>27.804</td>
      <td>296239.76</td>
      <td>296239.76</td>
      <td>296239.76</td>
    </tr>
    <tr>
      <th>2017-10-23</th>
      <td>29.00</td>
      <td>31.16</td>
      <td>29.79</td>
      <td>28.90</td>
      <td>466494.47</td>
      <td>1.46</td>
      <td>5.15</td>
      <td>27.743</td>
      <td>27.743</td>
      <td>27.743</td>
      <td>291977.10</td>
      <td>291977.10</td>
      <td>291977.10</td>
    </tr>
    <tr>
      <th>2017-10-20</th>
      <td>29.20</td>
      <td>29.83</td>
      <td>28.33</td>
      <td>27.85</td>
      <td>411570.12</td>
      <td>1.17</td>
      <td>4.31</td>
      <td>27.060</td>
      <td>27.060</td>
      <td>27.060</td>
      <td>233804.65</td>
      <td>233804.65</td>
      <td>233804.65</td>
    </tr>
    <tr>
      <th>2017-10-19</th>
      <td>25.61</td>
      <td>27.20</td>
      <td>27.16</td>
      <td>25.61</td>
      <td>180490.47</td>
      <td>1.47<

In [4]:
stock['high']  #取出列

date
2020-04-17    19.76
2020-04-16    19.61
2020-04-15    19.99
2020-04-14    19.36
2020-04-13    19.48
              ...  
2017-10-24    28.75
2017-10-23    31.16
2017-10-20    29.83
2017-10-19    27.20
2017-10-18    26.41
Name: high, Length: 533, dtype: float64

In [6]:
stock[0:5]  #取出列

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>close</th>
      <th>low</th>
      <th>volume</th>
      <th>price_change</th>
      <th>p_change</th>
      <th>ma5</th>
      <th>ma10</th>
      <th>ma20</th>
      <th>v_ma5</th>
      <th>v_ma10</th>
      <th>v_ma20</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-04-17</th>
      <td>19.50</td>
      <td>19.76</td>
      <td>19.52</td>
      <td>19.42</td>
      <td>30986.41</td>
      <td>0.08</td>
      <td>0.41</td>
      <td>19.386</td>
      <td>19.487</td>
      <td>19.372</td>
      <td>27932.33</td>
      <td>29716.51</td>
      <td>40609.42</td>
    </tr>
    <tr>
      <th>2020-04-16</th>
      <td>19.34</td>
      <td>19.61</td>
      <td>19.44</td>
      <td>19.25</td>
      <td>19242.38</td>
      <td>-0.07</td>
      <td>-0.36</td>
      <td>19.384</td>
      <td>19.495</td>
      <td>19.356</td>
      <td>28713.78</td>
      <td>30451.68</td>
      <td>42135.92</td>
    </tr>
    <tr>
      <th>2020-04-15</th>
      <td>19.35</td>
      <td>19.99</td>
      <td>19.51</td>
      <td>19.26</td>
      <td>42097.65</td>
      <td>0.16</td>
      <td>0.83</td>
      <td>19.410</td>
      <td>19.500</td>
      <td>19.344</td>
      <td>29794.98</td>
      <td>34737.28</td>
      <td>43578.49</td>
    </tr>
    <tr>
      <th>2020-04-14</th>
      <td>19.20</td>
      <td>19.36</td>
      <td>19.35</td>
      <td>19.12</td>
      <td>24102.21</td>
      <td>0.24</td>
      <td>1.26</td>
      <td>19.418</td>
      <td>19.559</td>
      <td>19.339</td>
      <td>27476.99</td>
      <td>42044.24</td>
      <td>44088.32</td>
    </tr>
    <tr>
      <th>2020-04-13</th>
      <td>19.48</td>
      <td>19.48</td>
      <td>19.11</td>
      <td>19.01</td>
      <td>23232.98</td>
      <td>-0.40</td>
      <td>-2.05</td>
      <td>19.500</td>
      <td>19.584</td>
      <td>19.361</td>
      <td>29939.95</td>
      <td>48381.43</td>
      <td>46148.55</td>
    </tr>
  </tbody>
</table>
</div>

In [7]:
stock['open'][0:5] #查看前5行的开盘价

date
2020-04-17    19.50
2020-04-16    19.34
2020-04-15    19.35
2020-04-14    19.20
2020-04-13    19.48
Name: open, dtype: float64

In [8]:
stock[0:5]['open']

date
2020-04-17    19.50
2020-04-16    19.34
2020-04-15    19.35
2020-04-14    19.20
2020-04-13    19.48
Name: open, dtype: float64

In [9]:
stock[['open','high','close','low']][0:5]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>close</th>
      <th>low</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-04-17</th>
      <td>19.50</td>
      <td>19.76</td>
      <td>19.52</td>
      <td>19.42</td>
    </tr>
    <tr>
      <th>2020-04-16</th>
      <td>19.34</td>
      <td>19.61</td>
      <td>19.44</td>
      <td>19.25</td>
    </tr>
    <tr>
      <th>2020-04-15</th>
      <td>19.35</td>
      <td>19.99</td>
      <td>19.51</td>
      <td>19.26</td>
    </tr>
    <tr>
      <th>2020-04-14</th>
      <td>19.20</td>
      <td>19.36</td>
      <td>19.35</td>
      <td>19.12</td>
    </tr>
    <tr>
      <th>2020-04-13</th>
      <td>19.48</td>
      <td>19.48</td>
      <td>19.11</td>
      <td>19.01</td>
    </tr>
  </tbody>
</table>
</div>

In [10]:
stock['open'].value_counts() #记录value出现的次数，并排序

23.91    4
24.60    4
24.40    4
24.00    4
29.00    4
        ..
32.26    1
20.70    1
21.06    1
16.54    1
27.70    1
Name: open, Length: 420, dtype: int64

In [14]:
high = stock['high'].value_counts()

In [15]:
type(high)

pandas.core.series.Series

In [16]:
high

24.95    5
24.30    4
24.25    4
22.15    3
24.48    3
        ..
17.23    1
22.31    1
28.04    1
31.07    1
20.25    1
Name: high, Length: 431, dtype: int64