In [3]:
import numpy as np

In [4]:
myArr  = np.arange(10)
myArr
print(myArr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
s = slice(2,7,2) # 2-7之间，不包含7，每次+2
print(type(s)) #class 'slice' 索引
myArr[s]

<class 'slice'>


array([2, 4, 6])

In [7]:
myArr[2:7:3]  # 等价与slice（2，7，3）

array([2, 5])

In [10]:
print(myArr[::]) 

[0 1 2 3 4 5 6 7 8 9]


In [11]:
myArr[4]

4

In [12]:
myArr[:]  #显示全部

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myArr[2:-1]  # stop在倒数第二个位置

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
myArr[2:5]

array([2, 3, 4])

In [6]:
myArr = np.arange(20)
myArr.shape=(4,5)
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
myArr[0] # 取出二维数组中的一维数组

array([0, 1, 2, 3, 4])

In [7]:
myArr[2][1:3] #取出二维数组中某一行的某一个序列

array([11, 12])

In [10]:
myArr[0:2]  #二维数组

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
myArr[0:2][0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
myArr[0:2][1:3]  #非横纵列筛选，还是在[0:2]筛选之后的二维数组上，再次进行[1;3]的筛选

array([[5, 6, 7, 8, 9]])

In [15]:
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
myArr[::2] # 2为步长

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [17]:
myArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
myArr[1,...] # 取出第二行

array([5, 6, 7, 8, 9])

In [19]:
myArr[...,1] # 取出第二列

array([ 1,  6, 11, 16])

In [20]:
myArr[1:3,...]  #1-2行

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
myArr[...,1:3] # 1-2列

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [22]:
myArr[0:2,1:3]

array([[1, 2],
       [6, 7]])