In [1]:
import numpy as np

In [2]:
myArr  = np.arange(10)
myArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
s = slice(2,7,2) # 2-7之间，不包含7，每次+2
print(type(s)) #class 'slice' 索引
myArr[s]

<class 'slice'>


array([2, 4, 6])

In [7]:
myArr[2:7:3]  # 等价与slice（2，7，3）

array([2, 5])

In [10]:
print(myArr[::]) 

[0 1 2 3 4 5 6 7 8 9]


In [11]:
myArr[4]

4

In [12]:
myArr[:]  #显示全部

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myArr[2:-1]  # stop在倒数第二个位置

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
myArr[2:5]

array([2, 3, 4])