In [3]:
import numpy as np
myArr = np.array([[0,1,2],[3,4,5],[6,7,8]])
myArr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
myData = myArr[[0,1,2],[0,1,2]] # 00,11,22 xy坐标
myData

array([0, 4, 8])

In [8]:
myData = myArr[[0,1,2],[2,1,0]] # 02,11,20 xy坐标
myData

array([2, 4, 6])

In [9]:
myArr = np.arange(12)
myArr.shape=(4,3)
myArr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
rows = np.array([[0,0],[3,2]])
cols = np.array([[0,2],[0,2]])
 

In [30]:
print(rows)  #行
print(cols) #列
print(myArr[rows,cols]) #矩阵的乘法

[[0 0]
 [3 2]]
[[0 2]
 [0 2]]
[[0 2]
 [9 8]]


In [31]:
myArr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
print(myArr[1:3,1:3]) #联合挖掘，1：3表示1-3之间（不包括3）

[[4 5]
 [7 8]]


In [34]:
print(myArr[1:3,[0,2]]) # 联合挖掘，同上，但[0,2]不表示区间，表示列，只表示列的0和2两个位置

[[3 5]
 [6 8]]


In [35]:
myArr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
myArr[myArr<5] #取出小于5

array([0, 1, 2, 3, 4])

In [39]:
myArr[myArr%2==0] #取出偶数

array([ 0,  2,  4,  6,  8, 10])

In [40]:
myArr[myArr%2 != 0] # 取出基数

array([ 1,  3,  5,  7,  9, 11])

In [41]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])  # ～为取补运算符，筛选无效数据

[1. 2. 3. 4. 5.]


In [42]:
a = np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]
