# numpy数组的广播，列数相同才能计算

In [3]:
import numpy as np

In [2]:
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])

In [3]:
print(a+b)

[ 3  7 11 15]


In [4]:
print(a-b)

[-1 -1 -1 -1]


In [5]:
print(a*b)

[ 2 12 30 56]


In [6]:
print(a/b)

[0.5        0.75       0.83333333 0.875     ]


In [8]:
a = np.array([1,3,5,7])
b = np.array([2,4,6,8,9])
print(a+b) #禁止形状不一致的计算

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [4]:
a = np.array([[1,3,5,7],[10,20,30,40]])
b = np.array([2,4,6,8])
print(a+b) #禁止形状不一致的计算,形状相同指的是列数一样

[[ 3  7 11 15]
 [12 24 36 48]]


In [6]:
print(a*b)

[[  2  12  30  56]
 [ 20  80 180 320]]
