In [1]:
import  numpy as np

In [2]:
np.random.binomial(100,0.5,20) 
#100次连续才做，其中0.5概率随机结果，接近50，20代表过程执行20次，得到20个结果

array([51, 48, 51, 50, 51, 50, 49, 50, 51, 46, 42, 42, 51, 48, 56, 62, 46,
       51, 52, 48])

In [3]:
np.random.binomial(100,0.5,5) 

array([56, 47, 36, 46, 52])

In [4]:
np.random.binomial(10000,0.5,5) 

array([5000, 5000, 4996, 5033, 5033])

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
path = '../YCdata/return300.csv'
return300 = pd.read_csv(path)
return300

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>return</th>
      <th>sig</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014/1/2</td>
      <td>-0.3454</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014/1/3</td>
      <td>-1.3436</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014/1/6</td>
      <td>-2.2762</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014/1/7</td>
      <td>-0.0284</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014/1/8</td>
      <td>0.1747</td>
      <td>1</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>240</th>
      <td>2014/12/25</td>
      <td>3.2514</td>
      <td>1</td>
    </tr>
    <tr>
      <th>241</th>
      <td>2014/12/26</td>
      <td>3.3105</td>
      <td>1</td>
    </tr>
    <tr>
      <th>242</th>
      <td>2014/12/29</td>
      <td>0.2791</td>
      <td>1</td>
    </tr>
    <tr>
      <th>243</th>
      <td>2014/12/30</td>
      <td>0.0607</td>
      <td>1</td>
    </tr>
    <tr>
      <th>244</th>
      <td>2014/12/31</td>
      <td>2.2025</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>245 rows × 3 columns</p>
</div>

In [10]:
ret = return300.iloc[:,1]
ret.head()

0   -0.3454
1   -1.3436
2   -2.2762
3   -0.0284
4    0.1747
Name: return, dtype: float64

In [12]:
p = len(ret[ret>0])/len(ret)
p

0.5306122448979592

In [13]:
1-p  # 下跌概率

0.4693877551020408

In [ ]:
stats.binoms.pmf(10,20,p)  #交易20天，连续10天下跌的概率