# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [5]:
x = np.arange(10) 

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
f = open('x.pkl','wb+') # wb: write binary

In [49]:
pickle.dump(x,f) # dump x to file f   use pickle to serialize x  to  the harddrive

In [8]:
!ls

Array.ipynb               ArrayMatrixOperator.ipynb
ArrayInputOutput.ipynb    x.pkl


In [41]:
#f  = open('x.pkl','rb')
f.seek(0);
pickle.load(f) # deserialize

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
pickle.load(f)

EOFError: Ran out of input

In [50]:
f.seek(0)

0

In [10]:
np.save('one_array',x) # serialized

In [11]:
!ls

Array.ipynb               ArrayMatrixOperator.ipynb x.pkl
ArrayInputOutput.ipynb    one_array.npy


In [13]:
np.load('one_array.npy') #deserialized

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = np.arange(10) 
y = np.arange(20)

In [17]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
np.savez('two_array',x,y)

In [24]:
!ls

Array.ipynb               one_array.npy             x.pkl
ArrayInputOutput.ipynb    two_array.npy
ArrayMatrixOperator.ipynb two_array.npz


In [25]:
np.load('two_array.npz')

In [26]:
c = np.load('two_array.npz')

In [27]:
c

In [28]:
c['x']

KeyError: 'x is not a file in the archive'

In [29]:
x = np.arange(10) 
y = np.arange(20)

np.savez('two_array',a=x,b=y)

In [31]:
np.load('two_array.npz')

In [32]:
c= np.load('two_array.npz')

In [33]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])