In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3])
b = np.array([3])
display(a,b,a+b)  # numy只要列一致，每个都加，即广告broadcast

array([1, 2, 3])

array([3])

array([4, 5, 6])

In [3]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s+1

0    2
1    3
2    4
3    5
dtype: int64

In [5]:
s2 = pd.Series([2])  # series与数值的加法，每个都加
s2

0    2
dtype: int64

In [6]:
s+s2  #仅仅匹配一个

0    3.0
1    NaN
2    NaN
3    NaN
dtype: float64

In [8]:
s.add(s2,fill_value = 0)


0    3.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [10]:
df1 = pd.DataFrame({'a':[1,2,3],
                    'b':[7,8,9]})
df1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>7</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>8</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>9</td>
    </tr>
  </tbody>
</table>
</div>

In [11]:
df2 = pd.DataFrame({'b':[1,2,3],
                    'c':[7,8,9]})
df2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>b</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>7</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>8</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>9</td>
    </tr>
  </tbody>
</table>
</div>

In [12]:
df1.add(df2) #dataframe 只加匹配的

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>NaN</td>
      <td>8</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NaN</td>
      <td>10</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NaN</td>
      <td>12</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

In [13]:
df1.add(df2,fill_value = 0)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.0</td>
      <td>8</td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2.0</td>
      <td>10</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3.0</td>
      <td>12</td>
      <td>9.0</td>
    </tr>
  </tbody>
</table>
</div>